version: "3"

services:
    ptg-web:
        restart: always
        container_name: "ptg-web" #容器名称
        build: ./next-project
        image: next #指定镜像
        ports:
            - 6776:6776
        depends_on:
            - ptg-server
            # - ptg-mysql

    ptg-server: #后端项目的service name
        restart: always
        container_name: "ptg-server"
        build: ./nest-project
        image: nest #指定镜像
        ports:
            - 6688:6688
        # depends_on:
        #     - ptg-mysql
        # links:
        #     - ptg-mysql
        # networks:
        #     - ptg-net
    # ptg-mysql:
    #     restart: always
    #     container_name: "ptg-mysql" #容器名称
    #     image: mysql:5.6
    #     command:
    #         --default-authentication-plugin=mysql_native_password
    #         --character-set-server=utf8mb4
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "123456"
    #         MYSQL_DATABASE: "ks"
    #     command:
    #         --default-authentication-plugin=mysql_native_password
    #         --character-set-server=utf8mb4
    #         --collation-server=utf8mb4_general_ci
    #         --explicit_defaults_for_timestamp=true
    #         --lower_case_table_names=1
    #     ports:
    #         - 3306:3306
    #     networks:
    #         - ptg-net
# networks:
#     ptg-net:
#         driver: bridge
